repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
    -   id: check-added-large-files
        args: ["--maxkb=2000"]
    -   id: check-executables-have-shebangs
    -   id: check-json
    -   id: check-toml
    -   id: check-merge-conflict
    -   id: detect-private-key
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.5.0
    hooks:
        # Run the linter.
        - id: ruff
          types_or: [ python, pyi, jupyter ]
          args: ["check", "--select", "I",  "--fix"]
        # Run the formatter.
        - id: ruff-format
    # Typo chceker for text files
# -   repo: https://github.com/crate-ci/typos
#     rev: v1.28.2
#     hooks:
#       - id: typos
